name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      AMINO_USERNAME: ${{secrets.AMINO_USERNAME}}
      AMINO_PASSWORD: ${{secrets.AMINO_PASSWORD}}
      CI: "true"
      GOPATH: ${{ github.workspace }}
      GO111MODULE: on
    steps:

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          path: ./src/github.com/${{ github.repository }}

      - name: Get dependencies
        working-directory: ./src/github.com/${{ github.repository }}
        run: |
          go mod download

      - name: Test
        working-directory: ./src/github.com/${{ github.repository }}
        run: make ci_run_test

  security:
    name: Security Checks
    runs-on: ubuntu-latest
    env:
      CI: "true"
      GOPATH: ${{ github.workspace }}
      GO111MODULE: on
    steps:

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          path: ./src/github.com/${{ github.repository }}

      - name: Get dependencies
        working-directory: ./src/github.com/${{ github.repository }}
        run: |
          go mod download & \
          curl -sfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sudo sh -s -- -b /usr/bin latest

      - name: Security Checks
        working-directory: ./src/github.com/${{ github.repository }}
        run: |
          gosec $GOPATH/src/github.com/AminoJS/AminoGo/aminogo & \
          gosec $GOPATH/src/github.com/AminoJS/AminoGo/test & \
          gosec $GOPATH/src/github.com/AminoJS/AminoGo/utils
